base_url: 
port: 443
ice_servers:
- urls:
  - 'stun:stun.l.google.com:19302'
  auth_type: secret
  auth_secret:
    username: test_user
    secret: test_secret
tls:
  cert: config/call.serviceline.flownform.com.crt
  key: config/call.serviceline.flownform.com.key
store:
  type: redis
  redis:
    host: localhost
    port: 6379
    prefix: peercalls
